// Mock API endpoint for localhost development
// Endpoint: GET /api/trips?from=MNL&to=MDR&date=2026-04-05

export default function handler(req, res) {
  const { from, to, date, passengers } = req.query;

  // Mock trips data
  const trips = [
    {
      trip_id: 'trip-001',
      vessel_name: 'MV Pacific Voyager',
      vessel_type: 'ferry',
      total_capacity: 500,
      deck_count: 4,
      vessel_year: 2018,
      last_survey_date: '2026-01-15',
      amenity_flags: ['restaurant', 'lounge', 'wifi'],
      departure_port: 'Manila Port Terminal',
      departure_code: from || 'MNL',
      departure_time: '08:00',
      arrival_port: 'Mindoro Port',
      arrival_code: to || 'MDR',
      arrival_time: '10:30',
      voyage_duration_minutes: 150,
      seats_total: 42,
      seats_available: 38,
      seats_reserved: 4,
      seats_deck: 'Deck 1-2 (Open deck)',
      seats_features: ['Open air seating', 'Ocean views', 'Ventilated'],
      seats_base_price: 690,
      seats_upgrades: { 'Extra Legroom': 150, 'Priority Boarding': 50 },
      beds_total: 28,
      beds_available: 22,
      beds_reserved: 6,
      beds_deck: 'Deck 2-3 (Cabin level)',
      beds_features: ['2-4 person berth', 'Climate-controlled', 'Private'],
      beds_base_price: 1200,
      beds_upgrades: { 'Breakfast Pack': 180 },
      cabins_total: 12,
      cabins_available: 10,
      cabins_reserved: 2,
      cabins_deck: 'Deck 4 (Premium suite)',
      cabins_features: ['Private ensuite', 'Queen-size bed', 'Entertainment'],
      cabins_base_price: 2890,
      cabins_upgrades: { 'Lounge Access': 200 }
    },
    {
      trip_id: 'trip-002',
      vessel_name: 'MV Island Express',
      vessel_type: 'catamaran',
      total_capacity: 350,
      deck_count: 2,
      vessel_year: 2020,
      last_survey_date: '2026-02-20',
      amenity_flags: ['wifi', 'restaurant'],
      departure_port: 'Manila Port Terminal',
      departure_code: from || 'MNL',
      departure_time: '14:00',
      arrival_port: 'Mindoro Port',
      arrival_code: to || 'MDR',
      arrival_time: '17:15',
      voyage_duration_minutes: 195,
      seats_total: 50,
      seats_available: 48,
      seats_reserved: 2,
      seats_deck: 'Deck 1 (Spacious cabin)',
      seats_features: ['Reclining seats', 'Air vents', 'USB charging'],
      seats_base_price: 890,
      seats_upgrades: { 'Premium Seat': 250 },
      beds_total: 18,
      beds_available: 14,
      beds_reserved: 4,
      beds_deck: 'Deck 2 (Cabin deck)',
      beds_features: ['2-person luxury', 'En-suite bathroom', 'Flat-screen TV'],
      beds_base_price: 1500,
      beds_upgrades: { 'Welcome Beverage': 100 },
      cabins_total: 8,
      cabins_available: 6,
      cabins_reserved: 2,
      cabins_deck: 'Deck 2 (Premium)',
      cabins_features: ['Luxury suite', 'King-size bed', 'Mini bar'],
      cabins_base_price: 3290,
      cabins_upgrades: { 'Personal Concierge': 500 }
    },
    {
      trip_id: 'trip-003',
      vessel_name: 'MV Sunset Cruise',
      vessel_type: 'ferry',
      total_capacity: 600,
      deck_count: 5,
      vessel_year: 2015,
      last_survey_date: '2025-12-10',
      amenity_flags: ['restaurant', 'lounge', 'wifi', 'medical'],
      departure_port: 'Manila Port Terminal',
      departure_code: from || 'MNL',
      departure_time: '18:00',
      arrival_port: 'Mindoro Port',
      arrival_code: to || 'MDR',
      arrival_time: '21:30',
      voyage_duration_minutes: 210,
      seats_total: 36,
      seats_available: 28,
      seats_reserved: 8,
      seats_deck: 'Deck 1-2 (Sunset deck)',
      seats_features: ['Sunset views', 'Open platform', 'Extended legroom'],
      seats_base_price: 1250,
      seats_upgrades: { 'Sunset Package': 300 },
      beds_total: 32,
      beds_available: 20,
      beds_reserved: 12,
      beds_deck: 'Deck 3 (Comfortable)',
      beds_features: ['Double berth', 'Private balcony', 'Shower'],
      beds_base_price: 1800,
      beds_upgrades: { 'Dinner Service': 250 },
      cabins_total: 20,
      cabins_available: 16,
      cabins_reserved: 4,
      cabins_deck: 'Deck 4-5 (Executive)',
      cabins_features: ['Master suite', 'Jacuzzi bath', 'Butler service'],
      cabins_base_price: 3990,
      cabins_upgrades: { 'Champagne Service': 600 }
    }
  ];

  // Simulate network delay
  setTimeout(() => {
    res.status(200).json(trips);
  }, 300);
}
